import type { MemoryCandidateRecord } from "../../db/memoryCandidates";
import type { MemoryRecord } from "../../types";
import { assessCandidateQuality } from "../../memory/candidateQuality";
import { ADMIN_BOARD_ROUTES } from "./routes";

export function renderCandidateBatchBar(candidates: MemoryCandidateRecord[]): string {
  if (!candidates.length) return "";
  return `<form id="candidate-batch-form" class="card m-batch-bar" method="POST" action="${ADMIN_BOARD_ROUTES.batchReviewCandidates.path}" onsubmit="return confirmCandidateBatch(event)"><div><strong>批量审核候选</strong><p>逐条处理勾选的候选；同意只执行当前仍满足条件的，其余跳过并计数。带校验警告的候选不会被批量同意，可用「人工确认通过选中项」强行执行（逐条记录人工决定）。</p></div><div class="m-batch-count">已选 <span id="candidate-batch-count">0</span> 条</div><div class="m-batch-actions"><button class="small-btn" type="button" onclick="toggleCandidateBatch(true)">全选当前页候选</button><button class="small-btn" type="button" onclick="toggleCandidateBatch(false)">取消选择</button><button class="action-btn approve-review" data-candidate-batch-submit type="submit" name="decision" value="approve" disabled>批量同意选中项</button><button class="action-btn approve-review" data-candidate-batch-submit type="submit" name="decision" value="override" disabled>人工确认通过选中项</button><button class="action-btn delete" data-candidate-batch-submit type="submit" name="decision" value="reject" disabled>批量拒绝选中项</button></div></form><script>function updateCandidateBatch(){const boxes=[...document.querySelectorAll('.candidate-batch-checkbox')];const count=boxes.filter(box=>box.checked).length;const label=document.getElementById('candidate-batch-count');if(label)label.textContent=String(count);document.querySelectorAll('[data-candidate-batch-submit]').forEach(button=>button.disabled=count===0)}function toggleCandidateBatch(checked){document.querySelectorAll('.candidate-batch-checkbox').forEach(box=>{box.checked=checked});updateCandidateBatch()}function confirmCandidateBatch(event){const count=document.querySelectorAll('.candidate-batch-checkbox:checked').length;if(!count)return false;const value=event.submitter&&event.submitter.value;if(value==='override')return confirm('确认以人工决定强行通过选中的 '+count+' 条候选？带校验警告的也会执行，并为每条记录人工越过校验。');const approving=value==='approve';return confirm(approving?('确认批量同意选中的 '+count+' 条候选？仍满足条件的会逐条执行，其余跳过。'):('确认批量拒绝选中的 '+count+' 条候选？不会修改任何记忆。'))}</script>`;
}

export function renderQualityBatchBar(candidates: MemoryCandidateRecord[]): string {
  if (!candidates.some((candidate) => assessCandidateQuality(candidate).label !== "pass")) return "";
  return `<form id="quality-batch-form" class="card m-batch-bar" method="POST" action="${ADMIN_BOARD_ROUTES.batchRejectCandidateQuality.path}" onsubmit="return confirmQualityBatch()"><div><strong>原子质量审计</strong><p>只会拒绝你勾选的低质量候选；不会新增、更新或删除任何正式记忆。</p></div><div class="m-batch-count">已选 <span id="quality-batch-count">0</span> 条</div><div class="m-batch-actions"><button class="small-btn" type="button" onclick="toggleQualityBatch(true)">全选质量问题</button><button class="small-btn" type="button" onclick="toggleQualityBatch(false)">取消选择</button><button class="action-btn delete" data-quality-batch-submit type="submit" disabled>批量拒绝选中项</button></div></form><script>function updateQualityBatch(){const boxes=[...document.querySelectorAll('.quality-batch-checkbox')];const count=boxes.filter(box=>box.checked).length;const label=document.getElementById('quality-batch-count');if(label)label.textContent=String(count);document.querySelectorAll('[data-quality-batch-submit]').forEach(button=>button.disabled=count===0)}function toggleQualityBatch(checked){document.querySelectorAll('.quality-batch-checkbox').forEach(box=>{box.checked=checked});updateQualityBatch()}function confirmQualityBatch(){const count=document.querySelectorAll('.quality-batch-checkbox:checked').length;return count>0&&confirm('确认拒绝选中的 '+count+' 条低质量候选？不会修改任何正式记忆。')}</script>`;
}

export function renderFactBatchBar(candidates: MemoryCandidateRecord[]): string {
  if (!candidates.some((candidate) => candidate.action === "diary_split_fact" && candidate.status === "pending")) return "";
  return `<form id="fact-batch-form" class="card m-batch-bar" method="POST" action="${ADMIN_BOARD_ROUTES.batchReviewCandidateFacts.path}" onsubmit="return confirmFactBatch(event)"><div><strong>批量审核日记事实</strong><p>只处理勾选的事实候选，不会碰 Dream 的更新、删除或其他建议。</p></div><div class="m-batch-count">已选 <span id="fact-batch-count">0</span> 条</div><div class="m-batch-actions"><button class="small-btn" type="button" onclick="toggleFactBatch(true)">全选事实候选</button><button class="small-btn" type="button" onclick="toggleFactBatch(false)">取消选择</button><button class="action-btn approve-review" data-fact-batch-submit type="submit" name="decision" value="approve" disabled>批准选中的事实</button><button class="action-btn delete" data-fact-batch-submit type="submit" name="decision" value="reject" disabled>拒绝选中的事实</button></div></form><script>function updateFactBatch(){const boxes=[...document.querySelectorAll('.fact-batch-checkbox')];const count=boxes.filter(box=>box.checked).length;const label=document.getElementById('fact-batch-count');if(label)label.textContent=String(count);document.querySelectorAll('[data-fact-batch-submit]').forEach(button=>button.disabled=count===0)}function toggleFactBatch(checked){document.querySelectorAll('.fact-batch-checkbox').forEach(box=>{box.checked=checked});updateFactBatch()}function confirmFactBatch(event){const count=document.querySelectorAll('.fact-batch-checkbox:checked').length;if(!count)return false;const approving=event.submitter&&event.submitter.value==='approve';return confirm(approving?('确认新增选中的 '+count+' 条事实记忆？原日记不会改变。'):('确认拒绝选中的 '+count+' 条事实候选？不会写入记忆。'))}</script>`;
}

export function renderDreamReviewBatchBar(records: MemoryRecord[]): string {
  if (!records.some((record) => record.type === "dream_review" && record.status === "active")) return "";
  return `<form id="dream-review-batch-form" class="card m-batch-bar" method="POST" action="${ADMIN_BOARD_ROUTES.batchDreamReview.path}" onsubmit="return confirmDreamReviewBatch(event)"><div><strong>批量审核 Dream 提案</strong><p>逐条执行勾选的提案；每条独立生效，失败的会被跳过并在提示中计数。信息不足的提案请单独审。</p></div><div class="m-batch-count">已选 <span id="dream-review-batch-count">0</span> 条</div><div class="m-batch-actions"><button class="small-btn" type="button" onclick="toggleDreamReviewBatch(true)">全选当前页提案</button><button class="small-btn" type="button" onclick="toggleDreamReviewBatch(false)">取消选择</button><button class="action-btn approve-review" data-dream-review-batch-submit type="submit" name="decision" value="approve" disabled>批量同意选中项</button><button class="action-btn delete" data-dream-review-batch-submit type="submit" name="decision" value="reject" disabled>批量拒绝选中项</button></div></form><script>function updateDreamReviewBatch(){const boxes=[...document.querySelectorAll('.dream-review-batch-checkbox')];const count=boxes.filter(box=>box.checked).length;const label=document.getElementById('dream-review-batch-count');if(label)label.textContent=String(count);document.querySelectorAll('[data-dream-review-batch-submit]').forEach(button=>button.disabled=count===0)}function toggleDreamReviewBatch(checked){document.querySelectorAll('.dream-review-batch-checkbox').forEach(box=>{box.checked=checked});updateDreamReviewBatch()}function confirmDreamReviewBatch(event){const count=document.querySelectorAll('.dream-review-batch-checkbox:checked').length;if(!count)return false;const approving=event.submitter&&event.submitter.value==='approve';return confirm(approving?('确认批量同意选中的 '+count+' 条提案？目标记忆会按各提案内容更新、删除或替换。'):('确认批量拒绝选中的 '+count+' 条提案？原记忆不会改变。'))}</script>`;
}

export function renderMBatchBar(candidates: MemoryCandidateRecord[]): string {
  if (!candidates.some((candidate) => candidate.action === "m_relation_cleanup")) return "";
  return `<form id="m-batch-form" class="card m-batch-bar" method="POST" action="${ADMIN_BOARD_ROUTES.batchOperationalReview.path}" onsubmit="return confirmMBatch(event)"><div><strong>批量审核关系边</strong><p>只处理勾选的关系边；Z 事实取代和过期项目归档仍需逐条审核。</p></div><div class="m-batch-count">已选 <span id="m-batch-count">0</span> 条</div><div class="m-batch-actions"><button class="small-btn" type="button" onclick="toggleMBatch(true)">全选当前页关系边</button><button class="small-btn" type="button" onclick="toggleMBatch(false)">取消选择</button><button class="action-btn delete" data-batch-submit type="submit" name="decision" value="approve" disabled>只删选中的边</button><button class="action-btn approve-review" data-batch-submit type="submit" name="decision" value="reject" disabled>保留选中的边</button></div></form>`;
}

export const M_BATCH_SCRIPT = "function updateMBatch(){const boxes=[...document.querySelectorAll('.m-batch-checkbox')];const count=boxes.filter(box=>box.checked).length;const label=document.getElementById('m-batch-count');if(label)label.textContent=String(count);document.querySelectorAll('[data-batch-submit]').forEach(button=>button.disabled=count===0)}function toggleMBatch(checked){document.querySelectorAll('.m-batch-checkbox').forEach(box=>{box.checked=checked});updateMBatch()}function confirmMBatch(event){const count=document.querySelectorAll('.m-batch-checkbox:checked').length;if(!count)return false;const deleting=event.submitter&&event.submitter.value==='approve';return confirm(deleting?('确认只删除选中的 '+count+' 条关系边？A、B 两端记忆都不会改变。'):('确认保留选中的 '+count+' 条关系边？这些清理候选会被标记为已拒绝。'))}";
