import type { RuntimeVariables } from "./config/variables";

type GeneratedPlatformBindings = Pick<CloudflareBindings, "DB">;

/**
 * Platform bindings are generated by Wrangler. Dashboard variables are grouped
 * by business concern in `config/variables.ts`.
 */
export interface Env extends GeneratedPlatformBindings, RuntimeVariables {
  AI?: CloudflareBindings["AI"];
  MEMORY_QUEUE?: CloudflareBindings["MEMORY_QUEUE"] extends Queue<unknown> ? Queue<QueueMessage> : never;
  VECTORIZE?: CloudflareBindings["VECTORIZE"] | Vectorize;
}

export interface MemoryMaintenanceQueueMessage {
  type: "memory_maintenance";
  namespace: string;
  conversationId: string;
  fromMessageId: string;
  toMessageId: string;
  source: string;
  idempotencyKey: string;
}

export interface ConversationChunkQueueMessage {
  type: "conversation_chunk";
  namespace: string;
  conversationId: string;
  source: string;
  maxMessages?: number;
  idempotencyKey: string;
}

export interface RetentionQueueMessage {
  type: "retention";
  namespace: string;
  idempotencyKey: string;
}

export interface DiarySplitQueueMessage {
  type: "diary_split";
  namespace: string;
  diaryId: string;
  jobId: string;
}

export interface MemoryVectorSyncQueueMessage {
  type: "memory_vector_sync";
  namespace: string;
  memoryIds: string[];
  jobId: string;
}

export interface MemoryFiveAxisProjectionQueueMessage {
  type: "memory_five_axis_projection";
  namespace: string;
  memoryId: string;
  memoryUpdatedAt: string;
  memoryRevision?: number;
  outboxId: number;
  idempotencyKey: string;
}

export type QueueMessage =
  | MemoryMaintenanceQueueMessage
  | ConversationChunkQueueMessage
  | RetentionQueueMessage
  | DiarySplitQueueMessage
  | MemoryVectorSyncQueueMessage
  | MemoryFiveAxisProjectionQueueMessage;

export type Scope =
  | "chat:proxy"
  | "memory:read"
  | "memory:write"
  | "cache:read"
  | "cache:write"
  | "debug:read"
  | "export:read";

export type InjectionMode = "rag" | "full" | "hybrid" | "none";
export type MemoryMode = "external" | "builtin" | "hybrid" | "none";

export interface KeyProfile {
  source: string;
  namespace: string;
  scopes: Scope[];
  injectionMode: InjectionMode;
  memoryMode: MemoryMode;
  allowModelPassthrough: boolean;
  debug: boolean;
}

export interface AuthResult {
  ok: true;
  profile: KeyProfile;
  keyName: "CHATBOX_API_KEY" | "IM_API_KEY" | "DEBUG_API_KEY" | "MEMORY_MCP_API_KEY" | "GUIDE_DOG_API_KEY";
}

export interface OpenAIChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string | Array<unknown> | null;
  created_at?: string;
  name?: string;
  reasoning_content?: string;
  tool_call_id?: string;
  tool_calls?: unknown;
}

export interface OpenAIChatRequest {
  model: string;
  messages: OpenAIChatMessage[];
  stream?: boolean;
  temperature?: number;
  max_tokens?: number;
  [key: string]: unknown;
}

export interface OpenAIChatChoice {
  index?: number;
  message?: OpenAIChatMessage;
  finish_reason?: string | null;
  [key: string]: unknown;
}

export interface OpenAIChatResponse {
  id?: string;
  object?: string;
  created?: number;
  model?: string;
  choices?: OpenAIChatChoice[];
  usage?: TokenUsage;
  [key: string]: unknown;
}

export interface TokenUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  input_tokens?: number;
  output_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_read_input_tokens?: number;
  [key: string]: unknown;
}

export interface Conversation {
  id: string;
  namespace: string;
  created_at: string;
  updated_at: string;
}

export interface MessageRecord {
  id: string;
  conversation_id: string;
  namespace: string;
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  source: string | null;
  created_at: string;
}

export interface MemoryRecord {
  id: string;
  namespace: string;
  type: string;
  content: string;
  summary: string | null;
  fact_key: string | null;
  active_fact: number;
  thread: string | null;
  risk_level: string | null;
  urgency_level: string | null;
  tension_score: number | null;
  response_posture: string | null;
  audit_state: string | null;
  valence: number | null;
  arousal: number | null;
  importance: number;
  confidence: number;
  status: "active" | "deleted" | "superseded" | "low_confidence" | string;
  pinned: number;
  tags: string | null;
  source: string | null;
  source_message_ids: string | null;
  vector_id: string | null;
  vector_synced: number;
  vector_sync_status?: "synced" | "failed" | "pending" | "deleted" | null;
  last_recalled_at: string | null;
  recall_count: number;
  five_axis_revision?: number;
  created_at: string;
  updated_at: string;
  expires_at: string | null;
}

export interface MemoryApiRecord {
  id: string;
  namespace: string;
  type: string;
  content: string;
  summary: string | null;
  fact_key: string | null;
  active_fact: boolean;
  thread: string | null;
  risk_level: string | null;
  urgency_level: string | null;
  tension_score: number | null;
  response_posture: string | null;
  audit_state: string | null;
  valence: number | null;
  arousal: number | null;
  importance: number;
  confidence: number;
  status: string;
  pinned: boolean;
  tags: string[];
  source: string | null;
  source_message_ids: string[];
  vector_id: string | null;
  last_recalled_at: string | null;
  recall_count: number;
  created_at: string;
  updated_at: string;
  expires_at: string | null;
  score?: number;
}

export interface SummaryRecord {
  id: string;
  namespace: string;
  conversation_id: string | null;
  content: string;
  from_message_id: string | null;
  to_message_id: string | null;
  message_count: number;
  vector_id: string | null;
  created_at: string;
  updated_at: string;
}

